### ISSUE TITLE
Solution to lab inconsistent with lessons provided

### ISSUE THREAD

**Issue by robotriley** [learn-co-curriculum/phase-3-metaprogramming-triangle-classification-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/5208/assignments/199424?module_item_id=451106

### Concern

As a preface, this is an ongoing issue with many lessons and labs in this curriculum:

In working on the Triangle Classification Lab, I'm tasked with creating custom errors that triggered when certain arguments are passed.

The solution code to this lab demonstrates several strategies that are in no way laid out in the Canvas lessons intended to introduce the concepts of custom errors.

What am I to do? I've been warned time and again by technical coaches and instructors to never blindly copy + paste code that I don't comprehend. But the learning material isn't providing me with the tools to comprehend the acceptable answer.

### Additional Context

`def validate_triangle
    raise TriangleError unless sides_greater_than_zero? && valid_triangle_inequality?
  end`

nowhere in the preceding lesson does the lesson literature suggest the above strategy of housing custom errors in its own instance method.

### Suggested Changes

Update the curriculum to set up your student body for success.

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in
upcoming releases of the Phase 3 curriculum.

As always, thanks for contributing! 💙
